apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: morphling-mysql
  namespace: morphling-system
  labels:
    type: local
    app: morphling
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
